kind: pipeline
type: docker
name: python

steps:
- name: init
  image: python:2.7.18-buster
  commands:
  - lscpu

  kind: pipeline
type: docker
name: python

steps:
- name: init1
  image: python:2.7.18-buster
  commands:
  - lscpu

